---
- name: Install common applications
  ansible.builtin.apt:
    name:
      - blueman
      - gparted
      - libreoffice-base
      - qbittorrent
      - redshift-gtk
      - sxiv
      - texinfo
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-volman
      - vim
      - wine
      - zathura
    state: present
    update_cache: true
    install_recommends: false
  tags:
    - pkg
    - pkg_apps
