- name: Configure my laptop
  hosts: localhost
  connection: local
  vars:
    machine_type: "laptop"
  roles:
    - role: xdg
    - role: dotfiles
    - role: packages
    - role: authentication
    - role: development
    - role: rice
